name: Add Status Check

on:
  status:

jobs:
  add_status_links:
    runs-on: ubuntu-latest
    steps:
      - name: Add Status Check Runner
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context)
