name: Add Status Check

on:
  status:

jobs:
  add_status_links:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        STATUS_CHECKS: ["ci/circleci: docker"]
    steps:
      - name: Add Status Check Runner
        if: ${{ matrix.STATUS_CHECKS == github.event.context }}
        # if need to upgrade see https://github.com/actions/github-script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {payload, ref } = context;
            const { repository, commit } = payload;
            const statusName = payload.context;
            const state = payload.state;
            const repo = repository.name;

            const sha = commit.sha;
            const owner = repository.owner;
            const branch = ref.replace("refs/heads/", "");
            const link = `https://griffa.dev`;
            console.table({statusName, state, repo, branch });
            const description = `My special link for ${statusName}`;
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state,
              description,
              target_url: state === "pending" ? null: link,
              icon_url: 'https://playwright.dev/img/playwright-logo.svg',
              context: "My special link"
            });
