name: Add Status Check

on:
  status:

jobs:
  add_status_links:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        STATUS_CHECKS: ["ci/circleci: docker"]
    steps:
      - name: Add Status Check Runner
        if: ${{ matrix.STATUS_CHECKS == github.event.context }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(github, context);
            const payload = context.payload;
            const { repository } = payload;
            const statusName = payload.context;
            const status = payload.state;
            const repoName = repository.name;
            console.log(statusName, status, repoName);
